name: server

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Navigate to Server Directory
        run: cd server

      - name: Install Dependencies
        run: npm install
        working-directory: ./server

      - name: Lint Code
        run: npm run lint
        working-directory: ./server

      - name: Build Project
        run: npm run build
        working-directory: ./server