name: tests

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Navigate to Frontend Directory
        run: cd frontend

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Lint Code
        run: npm run lint
        working-directory: ./frontend

      - name: Build Project
        run: npm run build
        working-directory: ./frontend

  server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Navigate to Server Directory
        run: cd server

      - name: Install Dependencies
        run: npm install
        working-directory: ./server

      - name: Lint Code
        run: npm run lint
        working-directory: ./server

      - name: Build Project
        run: npm run build
        working-directory: ./server